### ISSUE TITLE
maven version inconsistancy

### ISSUE THREAD

**Issue by DALDEI** [mvysny/karibu-dsl#15]
The docs say to use the latest tag on github for the maven verison.  The latest tag says .0.5.2
The latest version on maven central I can find is 0.4.12
https://mvnrepository.com/artifact/com.github.vok.karibudsl/karibu-dsl-v8/0.4.12

**Comment by DALDEI** [comment]
I found this one ...
https://mvnrepository.com/artifact/com.github.mvysny.karibudsl/karibu-dsl-v8

Is that the correct repo/maven coordinates ?

**Comment by DALDEI** [comment]
Ignore - I didnt rtfm fully ... I think some of the examples still reference the old name ....
the new one is com.github.mvysny.karibudsl

**Comment by mvysny** [comment]
Yes, i had to repackage Karibu-DSL, in order to be able to publish it onto Maven Central. I couldn't prove ownership of com.github.vok domain...
The correct group ID is therefore `com.github.mvysny.karibudsl`
