### ISSUE TITLE
Update karibu-dsl to the latest version of vaadin

### ISSUE THREAD

**Issue by vlipovetskii** [mvysny/karibu-dsl#16]
Hi,

Please update karibu-dsl to the latest version of vaadin.
Thank you in advance

     +--- com.github.mvysny.karibudsl:karibu-dsl-v10:0.5.3
     |    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.11 -> 1.3.21 (*)
     |    +--- com.vaadin:vaadin-core:12.0.3 -> 12.0.5
     |    |    +--- com.vaadin:flow-server:1.2.4
     |    |    |    +--- com.vaadin:flow-push:1.2.4
...

**Comment by mvysny** [comment]
Hi, you can easily use any Vaadin version with your project, regardless of which version the DSL uses. Please see https://github.com/mvysny/karibu10-helloworld-application/blob/master/build.gradle.kts for More details. So there's usually no need to release new DSL with just a Vaadin version change. Of course if you're after some unreleased feature, just let me know and I'll add it.
Currently I'm waiting for Vaadin 13 to Be released, should be around the corner (13 beta 1 is already out). See #17

**Comment by mvysny** [comment]
KT 0.6.0 has just been released which supports Vaadin 13.0.0 (beta1) - that's the newest we can get ;)
