### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by dosindi** [mvysny/karibu-dsl#22]
This is not a bug on this artifact however am sourcing for a way to generate reports using karibu and JasperReports. Is there a way to integrate the two?

**Comment by mvysny** [comment]
Hi, the easiest way is to create a Link+Resource (for Vaadin 8) or Anchor (for Vaadin 14) with StreamSource; when the resource asks for an InputStream just produce the report from JasperReports as a PDF byte array and return that :+1:
