### ISSUE TITLE
README mentions missing CommonElementsView

### ISSUE THREAD

**Issue by jhult** [mvysny/karibu-dsl#44]
[CommonElementsView](https://github.com/mvysny/karibu-dsl/blob/master/example-v8/src/main/kotlin/com/example/v8/uitest/example/CommonElementsView.kt) no longer exists be is mentioned in the [README](https://github.com/mvysny/karibu-dsl/blob/master/README.md?plain=1#L40).

**Comment by mvysny** [comment]
Ouch, thank you for letting me know. The Vaadin 8 Gradle plugin is incompatible with Gradle 7 and it's not maintained anymore. Therefore I've decided to remove the Vaadin 8 example app from the newest Karibu-DSL. But let me go through the README and fix the link to a more appropriate file.
