### ISSUE TITLE
Vaadin 24

### ISSUE THREAD

**Issue by mvysny** [mvysny/karibu-dsl#53]
- Branch from master to 1.1.x and maintain the old Vaadin 23- version there
- Make master use Vaadin 24 only
- v-bump hibernate-validator to 8.0.0 and depend on `jakarta.el:jakarta.el-api:5.0.1`; remove all traces of javax stuff

blocker:
- Gradle plugin for Vaadin 24 has not been released yet; however there are instructions to use pre-release of the Gradle plugin
- https://github.com/mvysny/karibu-testing/issues/136

**Comment by vladimirfx** [comment]
24.0.0.rc2 is out now. Unfortunely v24 broke `tabs` DSL. Very waiting for adapted version.

Thank you!

**Comment by mvysny** [comment]
Thanks for the reminder! Sure thing, let me work on this tomorrow :+1:

**Comment by mvysny** [comment]
The example app is now working in Vaadin 24 :tada: 

Let me check for any new Vaadin 24 stuff that would benefit from having a DSL

**Comment by mvysny** [comment]
No new components found; closing this issue as fixed. Please open a new ticket if you find some API missing :+1: 

Support for Vaadin 24 will be available in Karibu-DSL 2.0.0+

**Comment by vladimirfx** [comment]
Just checked our apps - works like a charm! 
Thank you!
