### ISSUE TITLE
How to see the detailed description of compilation errors from github actions script, invoked by opening a PR in the repo ?

### ISSUE THREAD

**Issue by vlipovetskii** [mvysny/karibu-dsl#67]
Caused by: org.jetbrains.kotlin.gradle.tasks.CompilationErrorException: Compilation error. See log for more details

**Comment by mvysny** [comment]
Hi, I assume you're referring to https://github.com/mvysny/karibu-dsl/actions/runs/11417530319/job/31769957122 . The log is very verbose unfortunately (thanks to --stacktrace --info switches), but the error message can be seen slightly above the CompilationErrorException:
```
e: file:///Users/runner/work/karibu-dsl/karibu-dsl/karibu-dsl/src/main/kotlin/com/github/mvysny/karibudsl/v10/Router.kt:24:59 Unresolved reference 'RouteParameters'.
```
I could remove `--stacktrace` but then Gradle build-script-originated exceptions wouldn't include their stacktraces... but then again, the build scripts are solidified by now, so I could remove those. I'd like to keep `--info` though, it provides additional insight to a build failure when the failure isn't reproducible locally.

Please let me know if this answers your question.

**Comment by vlipovetskii** [comment]
Thank you! After your hint I saw the error line.
