### ISSUE TITLE
Proposal: Migrate all routerLink functions

### ISSUE THREAD

**Issue by vlipovetskii** [mvysny/karibu-dsl#69]
In order to support both VaadinIcon and custom Icon collections I suggest to migrate all functions like
`fun (@VaadinDsl HasComponents).routerLink(icon: VaadinIcon?, ...`
from VaadinIcon to IconFactory
`fun (@VaadinDsl HasComponents).routerLink(icon: IconFactory?, ...`

Please review a new code and example of usage in [Demo project for Vaadin routerLink](https://github.com/vlipovetskii/vaadin-router-link)

Please note: A new code is backward-compatible.

@mvysny if it's ok for you, I will prepare a PR.

**Comment by mvysny** [comment]
Yup, good idea, please go ahead with the PR 👍
