### ISSUE TITLE
karibu-dsl-v8 with the latest version of Vaadin 8.5.1

### ISSUE THREAD

**Issue by vlipovetskii** [mvysny/karibu-dsl#8]
Could you complile karibu-dsl-v8 with the latest version of Vaadin 8.5.1 and place to repository  ? Now karibu-dsl-v8 0.4.6 depends on 8.4.4. Thank's in advance.

**Comment by mvysny** [comment]
Sure, I will. Yet Karibu is compatible both with 8.4.x and 8.5.x so you can simply override Vaadin dependency version. Please see https://github.com/mvysny/karibu-helloworld-application for details

**Comment by mvysny** [comment]
Karibu-DSL 0.4.7 has been released, enjoy!

**Comment by vlipovetskii** [comment]
Thank you very much !
