### ISSUE TITLE
KotlinNPE on startup in toViewName

### ISSUE THREAD

**Issue by DALDEI** [mvysny/karibu-dsl#9]
Navigator.kt,  ViewProvider,  toViewName throws KotlinNPE if it cannot find the @AutoView annotation.
This can happen in mutiple ways, such as adding a @AutoView to a non-view class.
This last time was more tricky.  an anonymous derived class 
   
   val view = object :  AViewClassWithoutAnnotation() { } 

Suggest silently failing or logging, not NPE, if annotation cannot be found -- very hard to debug.

**Comment by mvysny** [comment]
Sorry about that :-) Karibu-DSL will still throw an exception, but at least it will point out the full class name.
